name: Release

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.cirrus.yml'
    branches:
      - 'test-builds'

jobs:

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      run: |
        if [[ ${GITHUB_EVENT_NAME} == "tag" ]]; then
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        else
          echo ::set-output name=tag::${GITHUB_SHA::7}
        fi
    - name: Building release
      run: |
        make TAG=${{ steps.tag.outputs.tag }} linux_release
#    - name: Upload release file
#      uses: actions/upload-artifact@v1
#      with:
#        name: poetry-${{ steps.tag.outputs.tag }}-linux.tar.gz
#        path: releases/poetry-${{ steps.tag.outputs.tag }}-linux.tar.gz
#    - name: Upload checksum file
#      uses: actions/upload-artifact@v1
#      with:
#        name: poetry-${{ steps.tag.outputs.tag }}-linux.sha256sum
#        path: releases/poetry-${{ steps.tag.outputs.tag }}-linux.sha256sum

  MacOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      run: |
       if [[ ${GITHUB_EVENT_NAME} == "tag" ]]; then
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        else
          echo ::set-output name=tag::${GITHUB_SHA::7}
        fi
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Poetry
      run: |
        python get-poetry.py -y
        source $HOME/.poetry/env
    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install --no-dev
    - name: Preparing Python executables
      run: |
        curl -L https://github.com/sdispater/python-binaries/releases/download/2.7.18/python-2.7.18.macos.tar.xz -o python-2.7.18.tar.xz
        curl -L https://github.com/sdispater/python-binaries/releases/download/3.5.9/python-3.5.9.macos.tar.xz -o python-3.5.9.tar.xz
        curl -L https://github.com/sdispater/python-binaries/releases/download/3.6.8/python-3.6.8.macos.tar.xz -o python-3.6.8.tar.xz
        curl -L https://github.com/sdispater/python-binaries/releases/download/3.7.6/python-3.7.6.macos.tar.xz -o python-3.7.6.tar.xz
        curl -L https://github.com/sdispater/python-binaries/releases/download/3.8.3/python-3.8.3.macos.tar.xz -o python-3.8.3.tar.xz
        curl -L https://github.com/sdispater/python-binaries/releases/download/3.9.5/python-3.9.5.macos.tar.xz -o python-3.9.5.tar.xz
        curl -L https://github.com/sdispater/python-binaries/releases/download/3.10.2/python-3.10.2.macos.tar.xz -o python-3.10.2.tar.xz
        tar -zxf python-2.7.18.tar.xz
        tar -zxf python-3.5.9.tar.xz
        tar -zxf python-3.6.8.tar.xz
        tar -zxf python-3.7.6.tar.xz
        tar -zxf python-3.8.3.tar.xz
        tar -zxf python-3.9.5.tar.xz
        tar -zxf python-3.10.2.tar.xz
    - name: Build specific release
      run: |
        source $HOME/.poetry/env
        poetry run python sonnet make release --ansi -P "2.7:python-2.7.18/bin/python" -P "3.5:python-3.5.9/bin/python" -P "3.6:python-3.6.8/bin/python" -P "3.7:python-3.7.6/bin/python" -P "3.8:python-3.8.3/bin/python" -P "3.9:python-3.9.5/bin/python" -P "3.10:python-3.10.2/bin/python"
#    - name: Upload release file
#      uses: actions/upload-artifact@v1
#      with:
#        name: poetry-${{ steps.tag.outputs.tag }}-darwin.tar.gz
#        path: releases/poetry-${{ steps.tag.outputs.tag }}-darwin.tar.gz
#    - name: Upload checksum file
#      uses: actions/upload-artifact@v1
#      with:
#        name: poetry-${{ steps.tag.outputs.tag }}-darwin.sha256sum
#        path: releases/poetry-${{ steps.tag.outputs.tag }}-darwin.sha256sum

  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      shell: bash
      run: |
        if [[ ${GITHUB_EVENT_NAME} == "tag" ]]; then
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        else
          echo ::set-output name=tag::${GITHUB_SHA::7}
        fi
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Poetry
      run: |
        python get-poetry.py -y
        $env:Path += ";$env:Userprofile\.poetry\bin"
    - name: Install dependencies
      run: |
        $env:Path += ";$env:Userprofile\.poetry\bin"
        poetry install --no-dev
    - name: Preparing Python executables
      run: |
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/2.7.17/python-2.7.17.windows.tar.xz -O python-2.7.17.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.5.4/python-3.5.4.windows.tar.xz -O python-3.5.4.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.6.8/python-3.6.8.windows.tar.xz -O python-3.6.8.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.7.6/python-3.7.6.windows.tar.xz -O python-3.7.6.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.8.3/python-3.8.3.windows.tar.xz -O python-3.8.3.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.9.5/python-3.9.5.windows.tar.xz -O python-3.9.5.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.10.2/python-3.10.2.windows.tar.xz -O python-3.10.2.tar.xz
        7z x python-2.7.17.tar.xz
        7z x python-3.5.4.tar.xz
        7z x python-3.6.8.tar.xz
        7z x python-3.7.6.tar.xz
        7z x python-3.8.3.tar.xz
        7z x python-3.9.5.tar.xz
        7z x python-3.10.2.tar.xz
        7z x python-2.7.17.tar
        7z x python-3.4.4.tar
        7z x python-3.5.4.tar
        7z x python-3.6.8.tar
        7z x python-3.7.6.tar
        7z x python-3.8.3.tar
        7z x python-3.9.5.tar
        7z x python-3.10.2.tar
    - name: Build specific release
      run: |
        $env:Path += ";$env:Userprofile\.poetry\bin"
        poetry run python sonnet make release --ansi -P "2.7:python-2.7.17\python.exe" -P "3.5:python-3.5.4\python.exe" -P "3.6:python-3.6.8\python.exe" -P "3.7:python-3.7.6\python.exe" -P "3.8:python-3.8.3\python.exe" -P "3.9:python-3.9.5\python.exe" -P "3.10:python-3.10.2\python.exe"
#    - name: Upload release file
#      uses: actions/upload-artifact@v1
#      with:
#        name: poetry-${{ steps.tag.outputs.tag }}-win32.tar.gz
#        path: releases/poetry-${{ steps.tag.outputs.tag }}-win32.tar.gz
#    - name: Upload checksum file
#      uses: actions/upload-artifact@v1
#      with:
#        name: poetry-${{ steps.tag.outputs.tag }}-win32.sha256sum
#        path: releases/poetry-${{ steps.tag.outputs.tag }}-win32.sha256sum
